### ISSUE TITLE
TooManyRedirects: Exceeded 30 redirects

### ISSUE THREAD

**Issue by koperfieldcz** [Sorien/plugin.video.sl#3]
Vyhazuje chybu, Kodi přesáhlo 30 přesměrování a nechce pokračovat, proto raději spadne. Log:
`16:36:01.123 T:1808 WARNING: CPythonInvoker(4, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\service.py): the python script "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\service.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
16:36:12.033 T:6924  NOTICE: [plugin.video.sl] Next update 2018-06-26 04:36:12.033000
16:36:15.368 T:6924   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.TooManyRedirects'>
                                            Error Contents: Exceeded 30 redirects.
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\service.py", line 90, in <module>
                                                monitor.tick()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\service.py", line 71, in tick
                                                self.update()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\service.py", line 44, in update
                                                channels = s.channels()
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\skylink.py", line 121, in channels
                                                'd': 3})
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 521, in get
                                                return self.request('GET', url, **kwargs)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 508, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 640, in send
                                                history = [resp for resp in gen] if allow_redirects else []
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 140, in resolve_redirects
                                                raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
                                            TooManyRedirects: Exceeded 30 redirects.
                                            -->End of Python script error report<--
16:36:15.423 T:6924 WARNING: CPythonInvoker(5, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\service.py): the python script "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.sl\service.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon`

**Comment by Sorien** [comment]
tuto chybu hlasi ak sa uz pozuivaju vsetky 4 zariadenia, mam niaky kod ktory to bude riesit pripraveny ale tento tyzden to zrejme nebude

**Comment by koperfieldcz** [comment]
Problém bude jinde.. Smazal jsem všechna zařízení a stejně to vyskočí.

**Comment by Sorien** [comment]
A nevymazal si náhodou aj to ktore používa plugin? V kodi/user_data/plugin.video.sl je súbor *.cookie malo by stačiť ho vymazat

**Comment by koperfieldcz** [comment]
Právěže ten tam nemám.. ve Windows jsem něco našel v appdata/Kodi/Addons/plugin.video.sl, ale soubor *.cookie ne

V userdata ani v program files, ani v appdata není nic (alespoň ve Win)

**Comment by Sorien** [comment]
sry az teraz som sa dostal za komp pozri c:\Users\user\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.sl\ mal by tam byt subor s koncovkou cookie

**Comment by koperfieldcz** [comment]
Našel jsem a už to šlape, dík za radu.
